#!/usr/bin/env bash

if [ -z "$1" ]
  then
    echo "Error : No file name supplied"
    exit 1
fi

FILE_NAME="$1.java"
INPUT_FILE="$1.txt"
CLASS_NAME="$1"

if [ -e "$FILE_NAME" ]
then
    echo "Error : File Already Exist"
else
    echo "import java.io.*;

public class $CLASS_NAME {
    BufferedReader bf;
    PrintWriter writer;
    StringBuilder sb;
    static boolean local_system = false;

    void run() throws IOException {
      
    }

    public static void main(String[] args) throws IOException {
        long start_time = System.currentTimeMillis();
        $CLASS_NAME obj = new $CLASS_NAME();
        obj.run();
        long end_time = System.currentTimeMillis();
        if (local_system) obj.writer.println(\"Time : \" + (end_time - start_time));
        obj.close();
    }

    public $CLASS_NAME(){
        writer = new PrintWriter(System.out);
        bf = new BufferedReader(new InputStreamReader(System.in));
        sb = new StringBuilder();
    }

    public int getInt() throws IOException {
        return Integer.parseInt(bf.readLine());
    }

    public long getLong() throws IOException {
        return Long.parseLong(bf.readLine());
    }

    public int[] ints() throws IOException {
        String[] data = bf.readLine().split(\" \");
        int[] send = new int[data.length];
        for (int i = 0, h = data.length; i < h; i++) send[i] = Integer.parseInt(data[i]);
        return send;
    }

    public long[] longs() throws IOException {
        String[] data = bf.readLine().split(\" \");
        long[] send = new long[data.length];
        for (int i = 0, h = data.length; i < h; i++) send[i] = Long.parseLong(data[i]);
        return send;
    }

    public void close() {
        writer.flush();
        writer.close();
    }
}

" > "$FILE_NAME"

echo "" > "$INPUT_FILE"
fi